# ================================================
# GitHub Actions 工作流配置
# 功能：每次 push 或 PR 时自动运行测试
# ================================================

name: API 自动化测试

# 什么时候触发这个工作流
on:
  push:
    branches: [ main, develop ]  # push 到这些分支时触发
  pull_request:
    branches: [ main ]           # PR 到 main 分支时触发
  workflow_dispatch:             # 允许手动触发

jobs:
  test:
    runs-on: ubuntu-latest       # 在 Ubuntu 虚拟机上运行

    steps:
    # ========== 1. 检出代码 ==========
    - name: 检出代码
      uses: actions/checkout@v4

    # ========== 2. 设置 Python 环境 ==========
    - name: 设置 Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # ========== 3. 缓存依赖（加速后续运行） ==========
    - name: 缓存 pip 依赖
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # ========== 4. 安装依赖 ==========
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests pydantic python-dotenv allure-pytest
        pip install fastapi uvicorn pyjwt httpx

    # ========== 5. 启动被测服务（后台运行） ==========
    - name: 启动 Demo API 服务
      run: |
        # 把 demo-api 的 main.py 复制到当前目录（或者你可以调整路径）
        cd ../demo-api || cd demo-api || echo "demo-api not found, using local main.py"
        nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
        # 等待服务启动
        sleep 5
        # 验证服务是否启动
        curl -f http://localhost:8000/docs || echo "Service may not be ready"
      working-directory: ${{ github.workspace }}
      continue-on-error: true

    # ========== 6. 运行冒烟测试 ==========
    - name: 运行冒烟测试 (Smoke)
      run: |
        pytest -m smoke -v --alluredir=allure-results
      continue-on-error: true   # 即使失败也继续，以便上传报告

    # ========== 7. 运行回归测试 ==========
    - name: 运行回归测试 (Regression)
      run: |
        pytest -m regression -v --alluredir=allure-results
      continue-on-error: true

    # ========== 8. 上传测试结果 ==========
    - name: 上传 Allure 结果
      uses: actions/upload-artifact@v4
      if: always()              # 即使测试失败也上传
      with:
        name: allure-results
        path: allure-results/
        retention-days: 30      # 保留 30 天

    # ========== 9. 生成测试报告摘要 ==========
    - name: 测试结果摘要
      if: always()
      run: |
        echo "## 测试结果" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ -d "allure-results" ]; then
          echo "✅ 测试已完成，结果已上传" >> $GITHUB_STEP_SUMMARY
          echo "请下载 Artifacts 查看 Allure 报告" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ 未找到测试结果" >> $GITHUB_STEP_SUMMARY
        fi